const fs = require("fs");

// 1. Создаём proxy.ts (Next.js 16 формат)
const proxyCode = [
  'import { NextRequest, NextResponse } from "next/server";',
  '',
  'export async function proxy(req: NextRequest) {',
  '  const { pathname } = req.nextUrl;',
  '',
  '  if (pathname === "/admin/login") {',
  '    return NextResponse.next();',
  '  }',
  '',
  '  if (pathname.startsWith("/admin")) {',
  '    const token = req.cookies.get("admin-token")?.value;',
  '',
  '    if (!token) {',
  '      return NextResponse.redirect(new URL("/admin/login", req.url));',
  '    }',
  '',
  '    try {',
  '      const parts = token.split(".");',
  '      const b64 = parts[0];',
  '      const sig = parts[1];',
  '      if (!b64 || !sig) {',
  '        return NextResponse.redirect(new URL("/admin/login", req.url));',
  '      }',
  '',
  '      const secret = process.env.ADMIN_SECRET || "dev-secret-change-me";',
  '      const encoder = new TextEncoder();',
  '      const key = await crypto.subtle.importKey(',
  '        "raw", encoder.encode(secret),',
  '        { name: "HMAC", hash: "SHA-256" }, false, ["sign"]',
  '      );',
  '      const sigBuf = await crypto.subtle.sign("HMAC", key, encoder.encode(b64));',
  '      const arr = new Uint8Array(sigBuf);',
  '      let binary = "";',
  '      for (let i = 0; i < arr.length; i++) { binary += String.fromCharCode(arr[i]); }',
  '      const raw = btoa(binary);',
  '      const expectedSig = raw.split("+").join("-").split("/").join("_").replace(/=+$/, "");',
  '',
  '      if (expectedSig !== sig) {',
  '        return NextResponse.redirect(new URL("/admin/login", req.url));',
  '      }',
  '',
  '      const decoded = atob(b64.split("-").join("+").split("_").join("/"));',
  '      const payload = JSON.parse(decoded);',
  '      if (Date.now() >= payload.exp) {',
  '        return NextResponse.redirect(new URL("/admin/login", req.url));',
  '      }',
  '',
  '      return NextResponse.next();',
  '    } catch {',
  '      return NextResponse.redirect(new URL("/admin/login", req.url));',
  '    }',
  '  }',
  '',
  '  return NextResponse.next();',
  '}',
  '',
  'export const config = {',
  '  matcher: ["/admin/:path*"],',
  '};',
].join("\n");

// Удаляем middleware.ts если есть
if (fs.existsSync("middleware.ts")) {
  fs.unlinkSync("middleware.ts");
  console.log("DELETED: middleware.ts");
}
fs.writeFileSync("proxy.ts", proxyCode);
console.log("OK: proxy.ts");

// 2. lib/admin-auth.ts (Edge-safe, без regex проблем)
const authCode = [
  'import { cookies } from "next/headers";',
  '',
  'const SECRET = process.env.ADMIN_SECRET || "dev-secret-change-me";',
  'const PASSWORD = process.env.ADMIN_PASSWORD || "natalia2026";',
  '',
  'function toBase64Url(str: string): string {',
  '  const encoder = new TextEncoder();',
  '  const bytes = encoder.encode(str);',
  '  let binary = "";',
  '  bytes.forEach(b => binary += String.fromCharCode(b));',
  '  const raw = btoa(binary);',
  '  return raw.split("+").join("-").split("/").join("_").replace(/=+$/, "");',
  '}',
  '',
  'function fromBase64Url(b64: string): string {',
  '  const padded = b64.split("-").join("+").split("_").join("/");',
  '  const binary = atob(padded);',
  '  const bytes = new Uint8Array(binary.length);',
  '  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);',
  '  return new TextDecoder().decode(bytes);',
  '}',
  '',
  'function uint8ToBase64Url(buf: Uint8Array): string {',
  '  let binary = "";',
  '  buf.forEach(b => binary += String.fromCharCode(b));',
  '  const raw = btoa(binary);',
  '  return raw.split("+").join("-").split("/").join("_").replace(/=+$/, "");',
  '}',
  '',
  'async function sign(payload: string): Promise<string> {',
  '  const encoder = new TextEncoder();',
  '  const key = await crypto.subtle.importKey(',
  '    "raw", encoder.encode(SECRET),',
  '    { name: "HMAC", hash: "SHA-256" }, false, ["sign"]',
  '  );',
  '  const sig = await crypto.subtle.sign("HMAC", key, encoder.encode(payload));',
  '  return uint8ToBase64Url(new Uint8Array(sig));',
  '}',
  '',
  'export async function createToken(): Promise<string> {',
  '  const payload = JSON.stringify({ role: "admin", exp: Date.now() + 24 * 60 * 60 * 1000 });',
  '  const b64 = toBase64Url(payload);',
  '  const sig = await sign(b64);',
  '  return b64 + "." + sig;',
  '}',
  '',
  'export async function verifyToken(token: string): Promise<boolean> {',
  '  try {',
  '    const parts = token.split(".");',
  '    const b64 = parts[0];',
  '    const sig = parts[1];',
  '    if (!b64 || !sig) return false;',
  '    const expected = await sign(b64);',
  '    if (expected !== sig) return false;',
  '    const data = JSON.parse(fromBase64Url(b64));',
  '    return Date.now() < data.exp;',
  '  } catch { return false; }',
  '}',
  '',
  'export function checkPassword(pwd: string): boolean {',
  '  return pwd === PASSWORD;',
  '}',
  '',
  'export async function getAdminSession(): Promise<boolean> {',
  '  try {',
  '    const jar = await cookies();',
  '    const token = jar.get("admin-token")?.value;',
  '    if (!token) return false;',
  '    return verifyToken(token);',
  '  } catch { return false; }',
  '}',
].join("\n");

fs.writeFileSync("lib/admin-auth.ts", authCode);
console.log("OK: lib/admin-auth.ts");

// 3. login route
const loginCode = [
  'import { NextRequest, NextResponse } from "next/server";',
  'import { checkPassword, createToken } from "@/lib/admin-auth";',
  '',
  'export async function POST(req: NextRequest) {',
  '  try {',
  '    const { password } = await req.json();',
  '',
  '    if (!checkPassword(password)) {',
  '      return NextResponse.json({ error: "Wrong password" }, { status: 401 });',
  '    }',
  '',
  '    const token = await createToken();',
  '    const res = NextResponse.json({ ok: true });',
  '',
  '    res.cookies.set("admin-token", token, {',
  '      httpOnly: true,',
  '      sameSite: "lax",',
  '      maxAge: 86400,',
  '      secure: process.env.NODE_ENV === "production",',
  '      path: "/",',
  '    });',
  '',
  '    return res;',
  '  } catch (e) {',
  '    console.error("Login error:", e);',
  '    return NextResponse.json({ error: "Server error" }, { status: 500 });',
  '  }',
  '}',
].join("\n");

fs.writeFileSync("app/api/admin/login/route.ts", loginCode);
console.log("OK: login/route.ts");

// 4. logout route
const logoutCode = [
  'import { NextResponse } from "next/server";',
  '',
  'export async function POST() {',
  '  const res = NextResponse.json({ ok: true });',
  '  res.cookies.set("admin-token", "", {',
  '    httpOnly: true,',
  '    sameSite: "lax",',
  '    maxAge: 0,',
  '    path: "/",',
  '  });',
  '  return res;',
  '}',
].join("\n");

fs.writeFileSync("app/api/admin/logout/route.ts", logoutCode);
console.log("OK: logout/route.ts");

console.log("\n=== ALL FIXES APPLIED ===");
